name: Docker Build and Push

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set timestamp tag
        id: set-timestamp
        run: echo "TIMESTAMP_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ismailtosun/reacttodo-techcareer:latest .
          docker tag ismailtosun/reacttodo-techcareer:latest ismailtosun/reacttodo-techcareer:${{ env.TIMESTAMP_TAG }}

      - name: Push Docker image to Docker Hub
        run: docker push ismailtosun/reacttodo-techcareer:latest && docker push ismailtosun/reacttodo-techcareer:${{ env.TIMESTAMP_TAG }}
  deploy-aws:
    runs-on: [aws]
    needs: build-and-push
    
    steps:
      - name: deploy to AWS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_URL }} '

          docker stop reacttodo-techcareer || true
          docker rm reacttodo-techcareer || true
          docker rmi ismailtosun/reacttodo-techcareer || true
          docker run -d -p 4016:80 --name reactapp ismailtosun/reacttodo-techcareer:latest
