name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:

  deploy-aws:
    runs-on: ubuntu-latest
    #needs: build-and-push
    
    steps:
      - uses: actions/checkout@v2 
      - name: deploy to AWS
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_URL}}

      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${HOSTNAME} '

            docker stop reacttodo-techcareer || true
            docker rm reacttodo-techcareer || true
            docker rmi ismailtosun/reacttodo-techcareer || true
            docker run -d -p 4016:80 --name reactapp ismailtosun/reacttodo-techcareer:latest
