name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:

  deploy-aws:
    runs-on: ubuntu-latest
    #needs: build-and-push
    
    steps:
      - name: deploy to AWS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_URL }} '

          docker stop reacttodo-techcareer || true
          docker rm reacttodo-techcareer || true
          docker rmi ismailtosun/reacttodo-techcareer || true
          docker run -d -p 4016:80 --name reactapp ismailtosun/reacttodo-techcareer:latest
